### ISSUE TITLE
Exception with unicode-urls in sitemap

### ISSUE THREAD

**Issue by justb81** [reevoo/sitemap_check#3]
My sitemap.xml contains links with unicode-characters (german umlauts). This tool execs with an fatal exception:
```
Checking https://www.xyz.ab/sitemap.xml
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "https://www.xyz.ab/meta/\u{fc}ber-uns" (URI::InvalidURIError)
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /usr/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/page.rb:11:in `initialize'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:68:in `new'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:68:in `block in pages'
	from /usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'
	from /usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'
	from /usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:68:in `map'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:68:in `pages'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:57:in `queue_pages'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check/sitemap.rb:20:in `check_pages'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:71:in `check_pages_in'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:66:in `block in check_pages'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:66:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:66:in `check_pages'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:25:in `check'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/lib/sitemap_check.rb:11:in `check'
	from /usr/lib/ruby/gems/2.3.0/gems/sitemap_check-0.1.10/bin/sitemap_check:5:in `<top (required)>'
	from /usr/bin/sitemap_check:22:in `load'
	from /usr/bin/sitemap_check:22:in `<main>'
```

**Comment by justb81** [comment]
seems to be this "bug": https://bugs.ruby-lang.org/issues/12852
